apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-mesh
spec:
  ingressClassName: nginx
  rules:
    - host: finance-mesh.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finance-mesh
                port:
                  number: 80
